### ISSUE TITLE
Title sets to default when blinded

### ISSUE THREAD

**Issue by mdogucu** [quarto-journals/jasa#4]
When `blinded` is set to true if there is a title set to something other than the default "Title" (e.g. "An interesting manuscript"), then the rendered version sets the title to "Title" instead of "An interesting manuscript".

**Comment by nicholasjhorton** [comment]
In case it's helpful, here's a reprex (change "blinded" to "true" and the correct title shows up).

```
---
title: "Teaching causal inference: moving beyond 'correlation does not imply causation'"
format:
  jasa-pdf:
    keep-tex: true  
    journal:
      blinded: true
  jasa-html: default
date: last-modified
author:
  - name: Nicholas Jon Horton
    affiliations:
      - name: Amherst College
        department: Department of Mathematics and Statistics
        orcid: 
abstract: |
  No abstract for editorial
keywords:
  - no keywords for editorial
bibliography: bibliography.bib  
---


Data science and statistics are tools that can help extract meaning from data.
However, the process of making decisions using data is complicated by many things, including sampling error (a major component of our curriculum) and non-sampling error (critical real-world issues less commonly taught that can all too easily lead to misleading findings).
As but one example of the latter, observed associations might be explained by other measured or unmeasured factors. 


## Disclosure statement

The authors have no conflicts of interest to declare.
```
