### ISSUE TITLE
Long affiliations go out of the page on pdf

### ISSUE THREAD

**Issue by ABohynDOE** [quarto-journals/jasa#5]
If I write long affiliations in the header of the `.qmd` file then it goes out of the page instead of going to the next line in the pdf output.

For example, if I write:

``` yaml
author:
  - name: Author 1 
    affiliations:
      - name: Univeristy of things, Somewhere
        department: Department of something, Faculty of big things
  - name: Author 2
    affiliations:
      - name: Univeristy of things, Somewhere
        department: Department of something, Faculty of big things
  - name: Author 3
    affiliations:
      - name: Univeristy of things, Somewhere
        department: Department of something, Faculty of big things
      - name: University of that, Somewhere else
        department: Department of other things, Faculty of bigger and smaller things
```

I obtain this output:

![image](https://user-images.githubusercontent.com/64012239/222474195-ec4d9ff4-bfe2-475d-a68c-8c52749b23e4.png)

instead of something like this where the affiliations automatically go to the next line when they're too long.

![image](https://user-images.githubusercontent.com/64012239/222474276-080435da-afcd-42bc-a398-54f1af3f2b28.png)
